### ISSUE TITLE
Bibliography file name

### ISSUE THREAD

**Issue by antaldaniel** [rstudio/bookdown-demo#22] opened 2017-11-23 10:42 UTC
This is not strictly a bookdown issue, but if you use bookdown on Windows, you will encounter similar problems and I believe for an average user like me it takes very long time to figure out some of them, because the error messages are very confusing in the workflow. 

I think this merits maybe a warning in the code, or at least a words in the documentation. 

```
This is BibTeX, Version 0.99d (MiKTeX 2.9.6500 64-bit)
The top-level auxiliary file: bookdown-demo.aux
The style file: apalike.bst
White space in argument---line 35 of file bookdown-demo.aux
 : \bibdata{book,packages,music\protect
 :                                      \TU\textunderscore report3}
```

I had a .bib filename music_report3.bib, and it gets some whitespace characters that create errors.  Similarly, if you have chunks that have hyphens, such as music-report can create problems. 

I am not experienced at all in LaTex, bookdown, which is probably my favorite package, brought me into using it, so figuring out these problems took me always a very-very-very long time. Maybe it would be a idea to add a table somewhere in the bookdown book, or some warnings that contain a table about avoidable variable / chunk / file / component naming that may cause a program in the interaction of bookdown / rmarkdown / knitr / external latex programs.

**Comment by yihui** [comment] 2017-11-23 16:47
Duplicate of https://github.com/rstudio/bookdown/issues/491

**Closed by yihui** 2017-11-23 16:47 UTC

**Comment by antaldaniel** [comment] 2017-11-23 17:10
Sorry about the duplication.
