### ISSUE TITLE
Safari not showing top menu

### ISSUE THREAD

**Issue by julovi** [rstudio/bookdown-demo#33] opened 2018-09-04 14:51 UTC
Hi,

Thank you for this wonderful tool. I've been able to download and compile successfully the demo and it renders just fine in Chrome (68.0.3440.106). However, when I open the demo in Safari (Version 11.1.2 (13605.3.8)), the top menu does not show up, so I can't use the search button, collapse the left menu, etc. Additionally,  when I open the online version (https://bookdown.org/yihui/bookdown-demo/), the demo looks fine, so it's only when I render the demo with Safari from my file system. 

Any ideas why this could be happening?

I'm sending screenshots of the three browsers in case my explanation is not clear. 

Thanks in advance for any cue on this.

[ChromeLocal.pdf](https://github.com/rstudio/bookdown-demo/files/2349110/ChromeLocal.pdf)
[SafariOnline.pdf](https://github.com/rstudio/bookdown-demo/files/2349111/SafariOnline.pdf)
[SafariLocal.pdf](https://github.com/rstudio/bookdown-demo/files/2349112/SafariLocal.pdf)

**Comment by yihui** [comment] 2018-09-04 15:35
Duplicate of https://github.com/rstudio/bookdown/issues/353

**Closed by yihui** 2018-09-04 15:35 UTC

**Comment by julovi** [comment] 2018-09-04 15:38
Thanks yihui, I understand now that I should use a server to see the top menu. Interestingly in my case, even when run locally, Chrome managed to show the menu correctly, opposed to  the case of  rstudio/bookdown#353.
